// Code generated by https://github.com/feihua/code_cli
// author：罗京生
// createTime：2024/12/25 10:01:11

use crate::vo::system::sys_dict_type_vo::{DictTypeReq, DictTypeResp, QueryDictTypeListReq};
use rbatis::rbdc::datetime::DateTime;
use serde::{Deserialize, Serialize};
/*
 *字典类型
 *author：罗京生
 *date：2024/12/25 10:01:11
 */
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DictType {
    pub id: Option<i64>,               //字典主键
    pub dict_name: String,             //字典名称
    pub dict_type: String,             //字典类型
    pub status: i8,                    //状态（0：停用，1:正常）
    pub remark: Option<String>,        //备注
    pub create_time: Option<DateTime>, //创建时间
    pub update_time: Option<DateTime>, //修改时间
}

impl From<DictTypeReq> for DictType {
    fn from(item: DictTypeReq) -> Self {
        let mut model = DictType {
            id: item.id,               //字典主键
            dict_name: item.dict_name, //字典名称
            dict_type: item.dict_type, //字典类型
            status: item.status,       //状态（0：停用，1:正常）
            remark: item.remark,       //备注
            create_time: None,         //创建时间
            update_time: None,         //修改时间
        };
        if let None = item.id {
            model.create_time = Some(DateTime::now());
        } else {
            model.update_time = Some(DateTime::now());
        }
        model
    }
}

impl Into<DictTypeResp> for DictType {
    fn into(self) -> DictTypeResp {
        DictTypeResp {
            id: self.id,                   //字典主键
            dict_name: self.dict_name,     //字典名称
            dict_type: self.dict_type,     //字典类型
            status: self.status,           //状态（0：停用，1:正常）
            remark: self.remark,           //备注
            create_time: self.create_time, //创建时间
            update_time: self.update_time, //修改时间
        }
    }
}
