// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// createTime：2024/12/25 10:01:11

use rbatis::RBatis;
use serde::{Deserialize, Serialize};

/*
 *用户与岗位关联
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct UserPost {
    pub user_id: i64, //用户id
    pub post_id: i64, //岗位id
}

